services:
  postgres_user_service:
    container_name: user-service-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    networks:
      - city-library-microservices
  mysql_book_service:
    container_name: book-service-mysql
    image: mysql
    environment:
      - MYSQL_DATABASE=CityLibraryBook
      - MYSQL_USER=book_user
      - MYSQL_PASSWORD=passwordbookuser
      - MYSQL_ROOT_PASSWORD=passwordroot
    ports:
      - 3306:3306
    networks:
      - city-library-microservices
  mongodb_book_reservation_service:
    container_name: book-reservation-service-mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - city-library-microservices
  redis_user_service:
    container_name: user-service-redis
    image: redis
    ports:
      - "5002:6379"
    networks:
      - city-library-microservices
  rabbitmq_service:
    container_name: rabbitmq-service
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - city-library-microservices
  user_service:
    container_name: user-service
    build:
      context: .
      dockerfile: src/UserServiceApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMqOptions__Host=rabbitmq_service
      - RabbitMqOptions__UserName=guest
      - RabbitMqOptions__Password=guest
      - RedisConnection__ConnectionString=redis_user_service
      - RedisConnection__InstanceName=CityLibrary_UserService_
      - DbConnectionString=Server=postgres_user_service:5432;User Id=postgres;Password=postgrespw;Database=CityLibrary
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 5101:80
    depends_on:
      - postgres_user_service
      - redis_user_service
      - rabbitmq_service
    networks:
      - city-library-microservices
  book_reservation_service:
    container_name: book_reservation_service
    build:
      context: .
      dockerfile: src/BookReservationReportApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:5555
      - RabbitMqOptions__Host=rabbitmq_service
      - RabbitMqOptions__UserName=guest
      - RabbitMqOptions__Password=guest
      - DbConnection__ConnectionString=mongodb://mongodb_book_reservation_service/CityLibraryReservations
      - DbConnection__DbName=CityLibraryReservations
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:5555
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 5103:80
      - 5555:5555
    depends_on:
      - mongodb_book_reservation_service
      - rabbitmq_service
    networks:
      - city-library-microservices
  book_service:
    container_name: book-service
    build:
      context: .
      dockerfile: src/BookServiceApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMqOptions__Host=rabbitmq_service
      - RabbitMqOptions__UserName=guest
      - RabbitMqOptions__Password=guest
      - DbConnectionString=server=mysql_book_service;port=3306;database=CityLibraryBook;user=book_user;password=passwordbookuser
      - ReservationServiceBaseUrl=http://book_reservation_service
      - BookReservationGrpcEndPoint=http://book_reservation_service:5555
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 5102:80
    depends_on:
      - mysql_book_service
      - rabbitmq_service
    networks:
      - city-library-microservices
  gateway_service:
    container_name: gateway-service
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
    networks:
      - city-library-microservices

networks:
  city-library-microservices:
    name: city-library-microservices
