services:
  mongodb_book_reservation_service:
    container_name: book-reservation-service-mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - city-library-microservices
  redis_user_service:
    container_name: user-service-redis
    image: redis
    ports:
      - "5002:6379"
    networks:
      - city-library-microservices

networks:
  city-library-microservices:
    name: city-library-microservices
